const KEY="mijn-kookboek-v1";
const DAYS=["Ma","Di","Wo","Do","Vr","Za","Zo"];
const demo=[
{id:"1",title:"Romige kip met spinazie",category:"Avondeten",servings:4,time:30,source:"",ingredients:["500 g kipfilet","200 ml room","150 g spinazie","2 teentjes knoflook","1 el olijfolie"],steps:["Snijd de kip in stukken.","Bak de kip goudbruin in olijfolie.","Voeg knoflook en spinazie toe.","Roer de room erdoor en laat 8 minuten zacht koken."],notes:"Lekker met rijst.",favorite:true,done:false},
{id:"2",title:"Citroenpasta",category:"Avondeten",servings:2,time:20,source:"",ingredients:["200 g pasta","1 citroen","50 g Parmezaan","100 ml room","Peper en zout"],steps:["Kook de pasta.","Rasp citroenschil en pers het sap.","Meng room, citroen en Parmezaan.","Schep de pasta door de saus."],notes:"Ook goed met courgette.",favorite:false,done:false}
];
let state=JSON.parse(localStorage.getItem(KEY)||"null")||{recipes:demo,shopping:[],plan:{}};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
function nav(view){$$(".view").forEach(x=>x.classList.toggle("active",x.id===view));$$(".bottomnav button").forEach(b=>b.classList.toggle("navactive",b.dataset.nav===view)); if(view==="home")renderHome(); if(view==="shopping")renderShopping(); if(view==="planner")renderPlanner(); if(view==="add")resetForm(); window.scrollTo(0,0)}
$$("[data-nav]").forEach(b=>b.addEventListener("click",()=>nav(b.dataset.nav)));
$("#addTop").onclick=()=>nav("add");

function cats(){return [...new Set(state.recipes.map(r=>r.category).filter(Boolean))].sort()}
function renderCats(){const s=$("#categoryFilter"),v=s.value;s.innerHTML='<option value="">Alle categorieën</option>'+cats().map(c=>`<option>${esc(c)}</option>`).join("");s.value=v;$("#quickFilters").innerHTML=cats().map(c=>`<button class="chip" data-cat="${esc(c)}">${esc(c)}</button>`).join("");$$(".chip").forEach(b=>b.onclick=()=>{s.value=b.dataset.cat;renderHome()})}
function renderHome(){renderCats();const q=$("#search").value.toLowerCase(),c=$("#categoryFilter").value;const rs=state.recipes.filter(r=>(!c||r.category===c)&&(!q||[r.title,r.category,...r.ingredients].join(" ").toLowerCase().includes(q)));$("#recipeGrid").innerHTML=rs.length?rs.map(card).join(""):`<div class="panel"><h3>Nog geen recepten</h3><p>Voeg je eerste recept toe via de knop hierboven.</p></div>`;$$(".card").forEach(x=>x.onclick=e=>{if(e.target.closest(".star"))return;openDetail(x.dataset.id)});$$(".star").forEach(x=>x.onclick=e=>{e.stopPropagation();toggleFav(x.dataset.id)})}
function card(r){return `<article class="card" data-id="${r.id}"><div class="cover">${emoji(r.category)}<button class="star" data-id="${r.id}">${r.favorite?"★":"☆"}</button></div><div class="cardbody"><h3>${esc(r.title)}</h3><div class="meta">${r.time||"?"} min · ${r.servings||"?"} porties · ${esc(r.category||"Andere")}</div><div class="tags"><span class="tag">${r.done?"✓ Gemaakt":"Nog te maken"}</span></div></div></article>`}
function openDetail(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;$("#detailContent").innerHTML=`<div class="detailhero"><div class="eyebrow" style="color:#d9e5da">${esc(r.category)}</div><h2>${esc(r.title)}</h2><div>${r.time||"?"} min · ${r.servings||"?"} porties</div><div class="detailactions"><button class="primary" onclick="toggleFav('${r.id}')">${r.favorite?"★ Favoriet":"☆ Favoriet"}</button><button class="ghost" onclick="editRecipe('${r.id}')">✎ Bewerken</button><button class="ghost" onclick="markDone('${r.id}')">${r.done?"✓ Al gemaakt":"✓ Markeer als gemaakt"}</button></div></div><div class="detailgrid"><div class="panel"><h3>Ingrediënten</h3><ul class="ingredients">${r.ingredients.map((x,i)=>`<li>${esc(x)} <button class="ghost" style="float:right;padding:0" onclick="addShop('${r.id}',${i})">＋</button></li>`).join("")}</ul></div><div class="panel"><h3>Bereiding</h3><ol class="steps">${(r.steps||[]).map(x=>`<li>${esc(x)}</li>`).join("")}</ol>${r.notes?`<h3>Notities</h3><p>${esc(r.notes)}</p>`:""}${r.source?`<p><a href="${esc(r.source)}" target="_blank" rel="noopener">Originele bron ↗</a></p>`:""}</div></div><div class="panel" style="margin-top:18px"><h3>Receptbeheer</h3><button class="ghost danger" onclick="deleteRecipe('${r.id}')">Verwijder recept</button></div>`;nav("detail");}
function toggleFav(id){const r=state.recipes.find(x=>x.id===id);if(r){r.favorite=!r.favorite;save();renderHome();if($("#detail").classList.contains("active"))openDetail(id)}}
function markDone(id){const r=state.recipes.find(x=>x.id===id);if(r){r.done=!r.done;save();openDetail(id)}}
function deleteRecipe(id){if(confirm("Recept verwijderen?")){state.recipes=state.recipes.filter(r=>r.id!==id);save();nav("home")}}
function addShop(id,i){const r=state.recipes.find(x=>x.id===id);if(r){state.shopping.push({id:crypto.randomUUID(),text:r.ingredients[i],done:false});save();alert("Toegevoegd aan boodschappenlijst.")}}
function editRecipe(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;nav("add");$("#editId").value=r.id;$("#title").value=r.title;$("#category").value=r.category;$("#servings").value=r.servings||4;$("#time").value=r.time||30;$("#source").value=r.source||"";$("#ingredients").value=r.ingredients.join("\n");$("#steps").value=(r.steps||[]).join("\n");$("#notes").value=r.notes||"";$("#saveRecipe").textContent="Wijzigingen bewaren"}
function resetForm(){["editId","title","source","ingredients","steps","notes"].forEach(id=>$("#"+id).value="");$("#servings").value=4;$("#time").value=30;$("#category").value="Avondeten";$("#saveRecipe").textContent="Recept bewaren";$("#importText").value=""}
$("#resetForm").onclick=resetForm;
$("#saveRecipe").onclick=()=>{const title=$("#title").value.trim();if(!title)return alert("Geef het recept een titel.");const id=$("#editId").value||crypto.randomUUID();const old=state.recipes.find(r=>r.id===id);const r={id,title,category:$("#category").value,servings:+$("#servings").value||4,time:+$("#time").value||0,source:$("#source").value.trim(),ingredients:lines($("#ingredients").value),steps:lines($("#steps").value),notes:$("#notes").value.trim(),favorite:old?.favorite||false,done:old?.done||false};state.recipes=old?state.recipes.map(x=>x.id===id?r:x):[r,...state.recipes];save();nav("home");openDetail(id)}
$("#parseImport").onclick=()=>{const t=$("#importText").value.trim();if(!t)return;const linesT=t.split(/\n+/).map(x=>x.trim()).filter(Boolean);const title=linesT.find(x=>!/^https?:\/\//i.test(x))?.replace(/^#+\s*/,"").slice(0,80)||"Nieuw recept";$("#title").value=title;$("#source").value=(t.match(/https?:\/\/\S+/)||[""])[0];const ing=linesT.filter(x=>/^\d|g\b|kg\b|ml\b|cl\b|el\b|tl\b|stuk|stuks|teentje|eetlepel|theelepel/i.test(x));$("#ingredients").value=ing.join("\n");$("#steps").value=linesT.filter(x=>!ing.includes(x)&&x!==title&&!/^https?:\/\//i.test(x)).join("\n");alert("De tekst is voorbereid. Controleer het recept en bewaar het. AI-herkenning volgt in de volgende stap.")};

function renderShopping(){const list=$("#shoppingList");list.innerHTML=state.shopping.length?state.shopping.map(x=>`<div class="shopitem ${x.done?"done":""}"><input type="checkbox" ${x.done?"checked":""} onchange="toggleShop('${x.id}')"><span>${esc(x.text)}</span><button class="ghost" onclick="delShop('${x.id}')">×</button></div>`).join(""):`<div class="panel"><p>Je boodschappenlijst is leeg.</p></div>`}
function toggleShop(id){const x=state.shopping.find(x=>x.id===id);if(x)x.done=!x.done;save();renderShopping()}function delShop(id){state.shopping=state.shopping.filter(x=>x.id!==id);save();renderShopping()}
$("#addShopping").onclick=()=>{const v=$("#shoppingInput").value.trim();if(v){state.shopping.push({id:crypto.randomUUID(),text:v,done:false});$("#shoppingInput").value="";save();renderShopping()}};$("#clearDone").onclick=()=>{state.shopping=state.shopping.filter(x=>!x.done);save();renderShopping()};

function renderPlanner(){const today=new Date(),mon=new Date(today);mon.setDate(today.getDate()-((today.getDay()+6)%7));$("#weekPlan").innerHTML=DAYS.map((d,i)=>{const dt=new Date(mon);dt.setDate(mon.getDate()+i);const key=dt.toISOString().slice(0,10);return `<div class="day"><h3>${d} ${dt.getDate()}/${dt.getMonth()+1}</h3>${(state.plan[key]||[]).map(id=>{const r=state.recipes.find(x=>x.id===id);return r?`<div class="planitem">${esc(r.title)}</div>`:""}).join("")}<button class="ghost" onclick="planDay('${key}')">＋ recept</button></div>`}).join("")}
function planDay(key){const names=state.recipes.map(r=>r.title);const answer=prompt("Welk recept wil je plannen?\n\n"+names.map((n,i)=>`${i+1}. ${n}`).join("\n"));const i=+answer-1;if(state.recipes[i]){state.plan[key]=[...(state.plan[key]||[]),state.recipes[i].id];save();renderPlanner()}}
$("#planAdd").onclick=()=>{const first=Object.keys(state.plan)[0]||new Date().toISOString().slice(0,10);planDay(first)}

$("#search").oninput=renderHome;$("#categoryFilter").onchange=renderHome;
function lines(s){return s.split(/\n+/).map(x=>x.trim()).filter(Boolean)}
function esc(s){return String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]))}
function emoji(c){return ({Dessert:"🍰",Bakwerk:"🥐",Soep:"🍲",Lunch:"🥗",Ontbijt:"🥞",BBQ:"🔥",Drank:"🥤"})[c]||"🍝"}
if("serviceWorker" in navigator) navigator.serviceWorker.register("sw.js").catch(()=>{});
renderHome();
